[BUG FIX] Cannot read property `getFilename` of undefined
TypeError: Cannot read property 'getFilename' of undefined at
isLintableFile (/node_modules/eslint-plugin-ember-best-practices/lib/rules/require-ember-lifeline.js:33:53)
at
MemberExpression (/node_modules/eslint-plugin-ember-best-practices/lib/rules/require-ember-lifeline.js:69:14)
at listeners.(anonymous
function).forEach.listener (/node_modules/eslint/lib/util/safe-emitter.js:47:58)
at Array.forEach ()